name: paperly
description: "A new Flutter project." 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.3.0
  device_info_plus: ^10.1.2
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.7.0
  eva_icons_flutter: ^3.1.0
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dio: ^5.0.9
  path_provider: ^2.0.11
  fpdart: ^1.1.0
  another_flushbar: ^1.12.30
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  palette_generator: ^0.3.3+4
  async_wallpaper: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24
 
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
